version: '3.8'

services:
  clinic_app:
    build: .
    image: clinic_app
    container_name: clinic_app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/clinic_app
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
      - SPRING_LIQUIBASE_ENABLED=true
      - SPRING_LIQUIBASE_CHANGE-LOG=classpath:db/changelog/db.changelog-master.yaml
    networks:
      - clinic-net

  # PostgreSQL
  postgres:
    image: postgres:15
    container_name: postgres-clinic_app
    environment:
      POSTGRES_DB: clinic_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - clinic-net
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d clinic_app"]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  clinic-net:
    driver: bridge

volumes:
  postgres-data: