
server:
  port: 9080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5433/clinic_app
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  #jpa:
    #hibernate:
   #   ddl-auto: create
   # show-sql: true
  #  properties:
 #     hibernate:
  #      format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

management:
  server:
    port: 8180
  endpoints:
    web:
      exposure:
        include: "*"